### ISSUE TITLE
Failed to resolve entry for package

### ISSUE THREAD

**Issue by markteekman** [astro-community/component-template#3]
I installed this template the way it's explained in the docs: 

```bash
# Initialize the Astro Component template in a new directory
npm init astro my-new-component-directory -- --template component
```

But when I try running the dev server using `npm start` I get the following error:

![Schermafbeelding 2022-04-09 om 10 40 20](https://user-images.githubusercontent.com/3909046/162564089-629e970b-7639-4580-bef6-81e02f077694.png)

Anything I should do differently?

**Comment by Princesseuh** [comment]
Hello!

This template is not related to the official `component` template available in the official repo

**Comment by markteekman** [comment]
Oh my bad @Princesseuh! Sorry about that 😅 I'll add an issue there and then delete this one shortly after 🙂
